services:
  postgres:
    image: postgres:16
    container_name: shop-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"

  backend:
    build: ./backend
    container_name: shop-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_NAME: shop
      DB_USER: shop
      DB_PASSWORD: shop123
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./frontend:/app/../frontend:ro
      - ./logs:/app/logs

  notify:
    build: ./backend
    container_name: shop-notify
    restart: unless-stopped
    command: python notify_worker.py
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./logs:/app/logs

volumes:
  postgres-data:
